import Head from "next/head";
import { gql } from "@apollo/client";
import client from "./apollo-client";
import HeroSection from "./home-page-components/HeroSection";
import AfterHeroSection from "./home-page-components/AfterHeroSection";

const HelloQuery = gql`
  query {
    hello
  }
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <HeroSection />
          <AfterHeroSection />
        </div>
      </main>
    </>
  );
}

export async function getStaticProps() {
  const { data } = await client.query({
    query: HelloQuery,
  });

  return {
    props: {
      data,
    },
  };
}
